### ISSUE TITLE
ui.py crashuje

### ISSUE THREAD

**Issue by dotmaxxx** [vladantrhlik/wocabee-bot#9]
ui.py sa otvori a hned sa vypne

**Comment by jacobsebek** [comment]
Zkus [můj fork](https://github.com/jacobsebek/wocabee-bot/tree/experimental), a v konzoli...

**Comment by dotmaxxx** [comment]
Aj ten to iste

a ked zapnem main.py tak vsetko funguje ale ked to zacne praca bota tak mi to da error

**Comment by jacobsebek** [comment]
Možná by pomohlo upřesnit jaký error

**Comment by dotmaxxx** [comment]
[2344:11096:0413/105219.364:ERROR:device_event_log_impl.cc(214)] [10:52:19.365] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.

-Toto este pri logine

Traceback (most recent call last):
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 289, in <module>
    elif (akce == 3): work_percent(baliky, selected_balik-1, f"{balik}.txt")
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 221, in work_percent
    do_the_hard_stuff(1,file)
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 155, in do_the_hard_stuff
    word = translate(word, file)
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 114, in translate
    f=open(file, "r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'Lektion4A,B.txt'

Toto pri vypracovavani (To iste aj pri ostatnych)

**Comment by jacobsebek** [comment]
Nemůže to najít ten soubor, musíš ho natrénovat než budeš vypracovávat.

**Comment by dotmaxxx** [comment]
ok

**Comment by dotmaxxx** [comment]
Ked chcem precvicit nahodi toto

Traceback (most recent call last):
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 285, in <module>
    if(akce == 1): train_balik(baliky,selected_balik-1, f"{balik}.txt")
  File "C:\Users\maxkr\Downloads\wocabee-bot-experimental\main.py", line 229, in train_balik
    baliky[balik].find_elements_by_tag_name('td')[0].find_element_by_tag_name("a").click()#.get_attribute('href')
  File "C:\Users\maxkr\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\maxkr\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\maxkr\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\maxkr\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable: element has zero size
  (Session info: chrome=89.0.4389.114)

**Comment by jacobsebek** [comment]
Tak to fakt nevim jak se může stát. Jseš sis jistej, že do toho browseru nesaháš? Měl bys to ovládat jen přes tu konzoli.

**Comment by IDK1854** [comment]
Dle mě, zase vydali nějakou aktualizaci, posledně co jsem cvičil balík tak jsem si ten balik.txt napsal sám, ale moc jsem to nezkoumal, nebyl čas.

**Comment by jacobsebek** [comment]
Jestli to je pravda, tak by to nemělo být těžký opravit, teď to ale dělat nebudu

**Comment by IDK1854** [comment]
@MaxX132 Zkus napsat ten soubor, pojmenuj ho (jmenobaliku).txt a zapiš tam ty slovíčka ve formátu 
Čech;Czech
Angličan;English
každé na nový řádek a zkus to spustit. Dej si ale pozor aby se ten balík nejmenoval Czech.txt.txt

**Comment by dotmaxxx** [comment]
Ok len to je nemcina a ako zistim ake su tie slovicka?

**Comment by IDK1854** [comment]
U těch balíku v Wocabee máš takově i-čko tak na to klikneš a máš tam ty slovíčka 
![image](https://user-images.githubusercontent.com/77778963/114535576-7d64b200-9c50-11eb-9117-b04d34f40cd0.png)

**Comment by dotmaxxx** [comment]
Diky

**Comment by dotmaxxx** [comment]
Ano funguje dakujem pekne :D

**Comment by kuvajtak12** [comment]
Čauko. Chcel by som sa opýtať ohľadom toho bota. Funguje to ešte alebo nema niekto náhou fix??

**Comment by IDK1854** [comment]
Zcela změnili způsob odesílání výsledků, takže je potřeba přepsat Python skript, už jsem tak v půlce, ale deadline mám do konce pololetí.

**Comment by kuvajtak12** [comment]
čauko akurát aj ja pracujem na tom. Len som slovak maybe. Robim to cez selenium. Lebo mám problem cez def. Neviem chybná library.

**Comment by kuvajtak12** [comment]
Nevie niekto mi poradiť ohľadom selenium. Potrebujem nastaviť ak tam to slovo není nech preskoči ten príkaz.

**Comment by IDK1854** [comment]
@kuvajtak12 Už jsi s tím botem nějak pokročil? Mě ještě zbývá pár typů v do_the_hard_work.

**Comment by kuvajtak12** [comment]
> @kuvajtak12 Už jsi s tím botem nějak pokročil? Mě ještě zbývá pár typů v do_the_hard_work.

Čauko aj hej aj nie. Skôr niekde hľadám ako urobiť databázu. Trénovanie. Neviem zadefinovať slovo. Počuj mohli by sme obidvaja na tom pracovať. Ak chceš. Napíš mi tvoj discord. Alebo si ma pridaj  A!R#1079

**Comment by kuvajtak12** [comment]
lebo ho robim od začiatku

**Comment by bufetar** [comment]
No čo pokročilo to dajako za tie dva roky? 😅
